### PR TITLE
add : response time logger

### PR DESCRIPTION
**Pull request by alexandreraulin**
Adding response time in logger

### CODE REVIEW

**Comment by hg-pyun** [comment]
I will merge to 2.6.0

**Comment by gaurav-sharma-gs** [comment]
@hg-pyun  - Do you plan to release this version anytime in future?

**Comment by hg-pyun** [comment]
@gaurav-sharma-gs Maybe this weekend.

**Review by hg-pyun — APPROVED** [review]

**Comment by hg-pyun** [comment]
@alexandreraulin Need resolving confilct

**Comment by hg-pyun** [comment]
@alexandreraulin Please send me the PR again.

**Pull request closed without merging**
