### PR TITLE
Add config log levels

### PR DESCRIPTION
**Pull request by rennanboni**
Hi, 

Would be possible to add log levels for custom output 
I add the levels configurations **log, debug, error, assert, trace, warn**, I know is a bit too much for what plugin really needs and use, we could cut to **log**, **debug** and **error** if you wish

But I wanted level **error** added so I could control in my app

What you think?

### CODE REVIEW

**Comment by hg-pyun** [comment]
@rennanboni 
Hello. Thank you for your good opinion.
Because loggers cannot predict how they will be used, they are abstracted and provided. I think it would be better to pass the parameters so that they can be distinguished within the logger function rather than by level. I think we'd better go over that feature a little bit more.

**Comment by rennanboni** [comment]
Hi @hg-pyun , 

Sorry for the delay, its been a busy month
Could you tell more about how the config would like

What I did understand is the config would look like this
```typescript
{
  "logger": {
    "onSuccess": (msg: string) => void,
    "onError": (msg: string) => void
  }
}
```

and the default would be 
```typescript
{
  "logger": {
    "onSuccess": console.log
    "onError": console.error
  }
}
```

This way the log would separate some kind "responsibility" and the log level control would be externalized

**Comment by hg-pyun** [comment]
@rennanboni 
The current design is dependent on the axios interface.
If you want to share the error function of request and response, you may want to use the following.
```js
instance.interceptors.request.use((request) => {
    return AxiosLogger.requestLogger(request, {
        logger: console.log
    });
}, (error) => {
    return AxiosLogger.errorLogger(error, {
        logger: conosole.error
    });
});
```
It would be more confusing to users if it were to be used as follows:
```js
{
  "logger": {
    "onSuccess": console.log
    "onError": console.error
  }
}
```

**Comment by rennanboni** [comment]
Hi @hg-pyun , 

Now I got it what you mean, I'll cancel this PR and create other with the follow changes

  - Add config options to **errorLogger**
  - Change requestLogger, responseLogger and errorLogger to use the printLog with **buildConfig** as optional and print log according what is available **buildConfig** or **GlobalConfig***

Thanks for the support

**Pull request closed without merging**
